#!/usr/bin/env python3
"""Generate compat/uclass_tab.h: the Unicode class and simple case mapping
of every code point, for libixcompat's <wctype.h> (UP-Term).

The Unicode version is the one vtcon's engine/vtwidth.h was generated from
(read from its header), so wcwidth and the classes come from one database.
UnicodeData.txt is fetched once into build/ucd/<version>/.
    python3 compat/gen_uclass.py [path/to/vtwidth.h]
        (default $VTCON/engine/vtwidth.h, VTCON default ~/Code/vtcon)

Layout (see uclass.c):
  ixc_class_run[]  sorted run starts, (first code point << 4) | class: a
                   code point's class is that of the last run starting at
                   or below it (binary search, 12 steps)
  ixc_upper/lower  case mapping runs {first, count, stride, delta}: code
                   points first, first+stride, ... (count of them) map to
                   themselves + delta
"""
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
VTWIDTH = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    os.environ.get("VTCON", os.path.expanduser("~/Code/vtcon")), "engine", "vtwidth.h")

CLASSES = ["CN", "LU", "LL", "LO", "M", "ND", "NO", "P", "S", "ZS", "ZL", "CC", "CF", "CS"]
GC = {"Lu": "LU", "Ll": "LL", "Lt": "LO", "Lm": "LO", "Lo": "LO",
      "Mn": "M", "Mc": "M", "Me": "M", "Nd": "ND", "Nl": "NO", "No": "NO",
      "Zs": "ZS", "Zl": "ZL", "Zp": "ZL", "Cc": "CC", "Cf": "CF", "Co": "CF",
      "Cs": "CS", "Cn": "CN"}
for g in ("Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po"):
    GC[g] = "P"
for g in ("Sm", "Sc", "Sk", "So"):
    GC[g] = "S"


def version():
    with open(VTWIDTH, encoding="utf-8") as f:
        m = re.search(r"from the Unicode ([0-9.]+) character database", f.read(2000))
    if not m:
        sys.exit("gen_uclass.py: no Unicode version in " + VTWIDTH)
    return m.group(1)


def unicodedata_txt(ver):
    cache = os.path.join(os.path.dirname(HERE), "build", "ucd", ver)
    path = os.path.join(cache, "UnicodeData.txt")
    if not os.path.exists(path):
        os.makedirs(cache, exist_ok=True)
        url = "https://www.unicode.org/Public/%s/ucd/UnicodeData.txt" % ver
        with urllib.request.urlopen(url) as r, open(path + ".part", "wb") as f:
            f.write(r.read())
        os.rename(path + ".part", path)
    return path


def case_runs(m):
    runs = []
    for c, t in sorted(m.items()):
        d = t - c
        if runs:
            first, count, stride, delta = runs[-1]
            if delta == d:
                if count == 1 and c - first in (1, 2):
                    runs[-1] = [first, 2, c - first, delta]
                    continue
                if count > 1 and c == first + count * stride:
                    runs[-1][1] += 1
                    continue
        runs.append([c, 1, 1, d])
    return runs


def main():
    ver = version()
    cls = ["CN"] * 0x110000
    upper, lower = {}, {}
    first = None
    with open(unicodedata_txt(ver), encoding="utf-8") as f:
        for line in f:
            fld = line.rstrip("\n").split(";")
            c, name, gc = int(fld[0], 16), fld[1], fld[2]
            if name.endswith(", First>"):
                first = c
                continue
            lo = first if name.endswith(", Last>") else c
            for x in range(lo, c + 1):
                cls[x] = GC[gc]
            if fld[12]:
                upper[c] = int(fld[12], 16)
            if fld[13]:
                lower[c] = int(fld[13], 16)
    runs = [(c, CLASSES.index(k)) for c, k in enumerate(cls) if c == 0 or k != cls[c - 1]]
    out = []
    w = out.append
    w("/* uclass_tab.h -- the Unicode class and simple case mapping of a code point.")
    w(" * GENERATED by compat/gen_uclass.py from the Unicode %s character database" % ver)
    w(" * (the version of vtcon's engine/vtwidth.h); do not edit, run the generator")
    w(" * (make -C compat tables). See uclass.c for the layout. */")
    w("")
    w("#define IXC_UNICODE_VERSION \"%s\"" % ver)
    w("")
    w("static const unsigned long ixc_class_run[%d] = {" % len(runs))
    for i in range(0, len(runs), 6):
        w("    " + " ".join("0x%07x," % (c << 4 | k) for c, k in runs[i:i + 6]))
    w("};")
    for name, m in (("ixc_upper", upper), ("ixc_lower", lower)):
        r = case_runs(m)
        w("")
        w("static const struct ixc_case_run %s[%d] = {" % (name, len(r)))
        for first_cp, count, stride, delta in r:
            w("    { 0x%05x, %d, %d, %d }," % (first_cp, count, stride, delta))
        w("};")
    path = os.path.join(HERE, "uclass_tab.h")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print("%s: Unicode %s, %d class runs, %d upper and %d lower case runs" % (
        path, ver, len(runs), len(case_runs(upper)), len(case_runs(lower))))


if __name__ == "__main__":
    main()
