/*
 * version.h file. Automatically generated by parse_version.
 */

#ifndef __VERSION_H__
#define __VERSION_H__

/* Commodities.h defines IX_VERSION too, so wait for our defines
   to come last, and undef the sucker now! */
#undef IX_VERSION

#define IX_NAME		"ixemul.library"
#ifdef TRACE_LIBRARY
#define IX_IDSTRING	"ixemul 80.0 [trace, 68000, soft-float, amigaos] (23.8.26)"
#else
#define IX_IDSTRING	"ixemul 80.0 [68000, soft-float, amigaos] (23.8.26)"
#endif
#define IX_VERSION	80
#define IX_REVISION	0
#define IX_PRIORITY	0

#endif
